name: wechat
on:
  workflow_dispatch:
    schedule:
      - cron: '0 8 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: Set up Python 3.7
         uses: actions/setup-python@v2
         with:
           python-version: 3.7.9
       - name: install pip packages
         run: |
           python -m pip install --upgrade pip
           pip3 install -r requirements.txt
      - name: wechat
        run: |
          python3 main.py
